Avoid iterator invalidation without effective insert
Tessil/sparse-map pull request #22
Opened 2022-08-30 15:38 UTC by artem

There's an issue with accessing an existing value with operator[] when
hashtable size reaches a certain value: iterator is sometimes being
invalidated leading to broken iterators invalidation contract:

> - insert, emplace, emplace_hint, operator[]: if there is an effective
> insert, invalidate the iterators.

or use-after-free from calling code if user is unaware of such behaviour.

Fix this issue by actually issuing a rehash in effective erase and insert
routines.

2022-08-30 15:40 UTC, artem commented
PS: docs also say that `erase()` always invalidates the iterators, though the current implementation does that only on effective erase. Should the doc be adjusted as well?

2022-09-09 19:16 UTC, Tessil requested changes

2022-09-09 19:16 UTC, Tessil commented on include/tsl/sparse_hash.h
> +            clear_deleted_buckets();
`clear_deleted_buckets` can throw an exception in some cases. A element could thus be correctly erased but the `erase` method could thus throw an exception which goes against the exception safety of the map.

2022-09-09 19:25 UTC, Tessil requested changes

2022-09-09 19:25 UTC, Tessil commented on include/tsl/sparse_hash.h
> +    if (m_sparse_buckets_data.empty()) {
These lines may not be needed. An empty `m_sparse_buckets_data` means that `m_sparse_buckets` points to `static_empty_sparse_bucket_ptr` and we will thus reach the later rehash call (just a bit slower on the first insertion but worth it for the simplicity).

2022-09-09 19:26 UTC, Tessil commented
Thank you, we effectively should avoid rehashing when no actual insert is done. 

I added some comments to the PR.

2022-09-14 13:03 UTC, artem commented
Thanks for the feedback. I have pushed fixes for review and additionally reverted `+ 1` in load threshold check to preserve original behaviour

2022-09-20 20:53 UTC, Tessil commented on tests/sparse_map_tests.cpp
> +   * Current map load threshold for rehashing is expected to be 52 elements.
The load rehash threshold is 51 not 52. I think though that the comment can eventually be removed.

2022-09-20 20:56 UTC, Tessil commented
Thank you for the change, looks good. Just a small comment left.

Note that the map doesn't guarantee that erase is `noexcept` per the commit message. The problem is more that an exception could be thrown during the rehash after an element was successfully erased which goes against the strong exception guarantee (see https://en.cppreference.com/w/cpp/language/exceptions). 

I also would like to limit the rehash to insertions as done in `std::unordered_map`

2023-01-06 21:40 UTC, artem commented
I think I have addressed all of your comments in the last revision and it is safe to merge. Also, I have squashed all the commits into a single one (since they no longer make sense on their own).

Sorry for the rather long delay, been busy with other things.

2023-01-15 15:28 UTC, Tessil approved these changes

2023-01-15 15:45 UTC, merged

2023-01-15 15:45 UTC, Tessil commented
Thank you, I merged the change.